# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awswho < Formula
  desc "Quickly output AWS sts get-caller-identity"
  homepage "https://github.com/jftuga/awswho"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_darwin_amd64.tar.xz"
      sha256 "6708b2b943ad07b923f117fc46f70905be30c7f2b682ee892357d4ea26aa79de"

      def install
        bin.install "awswho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_darwin_arm64.tar.xz"
      sha256 "d44937790359eced3d77c8e6aaf30e42b3991f409b3c087c93dc4bf8196745cc"

      def install
        bin.install "awswho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_linux_arm64.tar.xz"
      sha256 "60d56ae2bd466d00026c45348c5ce4d1a8184b27f85cfbc5bb0ca350d90f2d47"

      def install
        bin.install "awswho"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_linux_amd64.tar.xz"
      sha256 "a6669aed9bb2615f97276ca6515b0a833e0cc55c096dd17825c18dda8587461f"

      def install
        bin.install "awswho"
      end
    end
  end

  test do
    system "#{bin}/awswho -v"
  end
end
