# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awswho < Formula
  desc "Quickly output AWS sts get-caller-identity"
  homepage "https://github.com/jftuga/awswho"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_darwin_arm64.tar.xz"
      sha256 "38237cc2625cc5aa5a4fe02584e57c0cbf527b07eb507a1057455fd9fa777026"

      def install
        bin.install "awswho"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_darwin_amd64.tar.xz"
      sha256 "d8b7dc41d5da91649153b96deec8d86c2cac9643935ea44f8379c128f8c880ac"

      def install
        bin.install "awswho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_linux_arm64.tar.xz"
      sha256 "751e3c17cbe60aa09251f1f3959639aec48ed8a831fae6aa26253d48b3668852"

      def install
        bin.install "awswho"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/awswho/releases/download/v1.0.0/awswho_1.0.0_linux_amd64.tar.xz"
      sha256 "86301fa226ee392300a6a1aa040c0d8da7606833d6e05fc03aa05671117e0e25"

      def install
        bin.install "awswho"
      end
    end
  end

  test do
    system "#{bin}/awswho -v"
  end
end
