# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awswho < Formula
  desc "Output the results of the AWS sts get-caller-identity API"
  homepage "https://github.com/jftuga/awswho"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/aw/releases/download/v1.0.0/aw_1.0.0_darwin_arm64.tar.xz"
      sha256 "cd5c0701ae3472986077df1583b633ff3e5b30324c259eb6006e95a8f08af7dc"

      def install
        bin.install "awswho"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/aw/releases/download/v1.0.0/aw_1.0.0_darwin_amd64.tar.xz"
      sha256 "3e8798b667b4e4c54532db7006d8ec269a94fd218386a5cd522b6eb7b417ec57"

      def install
        bin.install "awswho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/aw/releases/download/v1.0.0/aw_1.0.0_linux_amd64.tar.xz"
      sha256 "d0b03adbbfdb4561cf7a29357491c680411f43b4e49fad060a0297597c7c9e68"

      def install
        bin.install "awswho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/aw/releases/download/v1.0.0/aw_1.0.0_linux_arm64.tar.xz"
      sha256 "7d79e2f734e64a7170f5e6435edf1f517843ee41b4fd416c3021b6cdda84385a"

      def install
        bin.install "awswho"
      end
    end
  end

  test do
    system "#{bin}/awswho -v"
  end
end
