# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changecase < Formula
  desc "convert command line arguments to upper, lower or title case"
  homepage "https://github.com/jftuga/changecase"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/changecase/releases/download/v1.2.0/changecase_1.2.0_darwin_arm64.tar.xz"
      sha256 "ed0005433eeb2b3188bef14229b4dc7a23c986243054bb6e5f3f68569332131d"

      def install
        bin.install "lower" "upper" "titlecase" "len"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/changecase/releases/download/v1.2.0/changecase_1.2.0_darwin_amd64.tar.xz"
      sha256 "30062d2ec5523076ff6e6019e4da3e1820e57528ef89366d53da6315627b6871"

      def install
        bin.install "lower" "upper" "titlecase" "len"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/changecase/releases/download/v1.2.0/changecase_1.2.0_linux_amd64.tar.xz"
      sha256 "cda1f7ab0dcfa98ef38e8662f04954fb593931518caf5fba37d16270d4eea348"

      def install
        bin.install "lower" "upper" "titlecase" "len"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/changecase/releases/download/v1.2.0/changecase_1.2.0_linux_arm64.tar.xz"
      sha256 "f32f9409f9eee3a7a084f7bd7c3c52a8d587e1a6711a9cd2fdab9c963319449e"

      def install
        bin.install "lower" "upper" "titlecase" "len"
      end
    end
  end

  test do
    system "#{bin}/lower TEST"
  end
end
