# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changecase < Formula
  desc "convert command line arguments to upper, lower or title case"
  homepage "https://github.com/jftuga/changecase"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/changecase/releases/download/v1.4.0/changecase_1.4.0_darwin_amd64.tar.xz"
      sha256 "58e9ee83f4f622acfb38c180bf07f2ecc94c46fd32b47fa41eb00d128e92fae5"

      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/changecase/releases/download/v1.4.0/changecase_1.4.0_darwin_arm64.tar.xz"
      sha256 "276c800c71a0350ae4346fbeaae71bf6f020cbeabace5313fe5b4e8918eebecd"

      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/changecase/releases/download/v1.4.0/changecase_1.4.0_linux_amd64.tar.xz"
      sha256 "78bef4ba266d9287fcc552e10559f874eb2924862422b8ade1984eb8891b67c8"
      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/changecase/releases/download/v1.4.0/changecase_1.4.0_linux_arm64.tar.xz"
      sha256 "aa3dc19608112bdef67dae7459692948d097c71b3d809edb9411d6cfdb22ad9b"
      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
  end

  test do
    system "#{bin}/lower TEST"
  end
end
