# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changecase < Formula
  desc "convert command line arguments to upper, lower or title case"
  homepage "https://github.com/jftuga/changecase"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/changecase/releases/download/v1.3.0/changecase_1.3.0_darwin_amd64.tar.xz"
      sha256 "18afffb9e52f7708f007b354aa266011cae004a99b8bdef6bb4ef7108b8a001b"

      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/changecase/releases/download/v1.3.0/changecase_1.3.0_darwin_arm64.tar.xz"
      sha256 "8fde191c569725e170ef5210f8e24e60848bc6cc83c14e8a8d96bf12ac27e38d"

      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/changecase/releases/download/v1.3.0/changecase_1.3.0_linux_amd64.tar.xz"
      sha256 "2e7b377937c124a7b694a5884d1884d18be93e6955ff13d4fff0a471c22dd227"
      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/changecase/releases/download/v1.3.0/changecase_1.3.0_linux_arm64.tar.xz"
      sha256 "44592eafb91a30d0bf998fdd40f50cc8c8b621a9ecf15e4a30600e3057b3f920"
      def install
        bin.install "lower"
        bin.install "upper"
        bin.install "titlecase"
        bin.install "len"
        bin.install "eq"
      end
    end
  end

  test do
    system "#{bin}/lower TEST"
  end
end
