# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chars < Formula
  desc "Determine the end-of-line format, tabs, bom, and nul characters"
  homepage "https://github.com/jftuga/chars"
  version "2.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/chars/releases/download/v2.4.1/chars_2.4.1_darwin_amd64.tar.xz"
      sha256 "193418eb06a27cd41f08d159af7a58a65a66c59a0221ac491d3b74d5762ee811"

      def install
        bin.install "chars"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/chars/releases/download/v2.4.1/chars_2.4.1_darwin_arm64.tar.xz"
      sha256 "0b3cadeaa3e813fda6afcaf7d806e358ee2bad18e54cb1816e2560a2d18b0a58"

      def install
        bin.install "chars"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/chars/releases/download/v2.4.1/chars_2.4.1_linux_amd64.tar.xz"
      sha256 "15edd28900132f680208d5d4ac086428f3a79aba03e687472f4a2bd4c0c05272"

      def install
        bin.install "chars"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/chars/releases/download/v2.4.1/chars_2.4.1_linux_arm64.tar.xz"
      sha256 "b0c6c4068c93059e343309d52b97b45256d48ab133c60d4a12c202815dd6d2dc"

      def install
        bin.install "chars"
      end
    end
  end

  test do
    system "#{bin}/chars -v"
  end
end
