# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chars < Formula
  desc "Determine the end-of-line format, tabs, bom, and nul characters"
  homepage "https://github.com/jftuga/chars"
  version "2.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/chars/releases/download/v2.6.0/chars_2.6.0_darwin_amd64.tar.xz"
      sha256 "dbb1a8e6b0e88066c91687121d51cd3854b69eed06d6aff45aea48d052aec927"

      def install
        bin.install "chars"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/chars/releases/download/v2.6.0/chars_2.6.0_darwin_arm64.tar.xz"
      sha256 "9f3dc0dc1e8d76a74b26a6d0db4e8dabc0001ab3d6577606840cef9cd56c0b51"

      def install
        bin.install "chars"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/chars/releases/download/v2.6.0/chars_2.6.0_linux_amd64.tar.xz"
        sha256 "7eb16f07f217b4ea7683cb31fb00d0a79a2680247319614bb21e815a9a05dfa8"

        def install
          bin.install "chars"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/chars/releases/download/v2.6.0/chars_2.6.0_linux_arm64.tar.xz"
        sha256 "6f17590818c7a37761807a328a57004738073cdfdf57726d4aff5122fb7c23b1"

        def install
          bin.install "chars"
        end
      end
    end
  end

  test do
    system "#{bin}/chars -v"
  end
end
