# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtdiff < Formula
  desc "dtdiff: output the difference between date, time or duration"
  homepage "https://github.com/jftuga/dtdiff"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_darwin_amd64.tar.xz"
      sha256 "911fb95b999d2423d5e4b971dd86e0c60a93c1cfc6da62422ed284259ec92475"

      def install
        bin.install "dtdiff"
      end
    end
    on_arm do
      url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_darwin_arm64.tar.xz"
      sha256 "d602a1db51ea81386f392932938d6471312db32e8c79e13045da2bc5940e003b"

      def install
        bin.install "dtdiff"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_linux_amd64.tar.xz"
        sha256 "222f0a6334f6953bf3deff6d5b6b16b8cdbfbb0aec522d77290325b12fc2e539"

        def install
          bin.install "dtdiff"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_linux_arm64.tar.xz"
        sha256 "f8c59908e25fc0deec9e97e684daeb17521aca2adf79abf6868d679321a0a1cf"

        def install
          bin.install "dtdiff"
        end
      end
    end
  end

  test do
    system "#{bin}/dtdiff -v"
  end
end
