# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtdiff < Formula
  desc "dtdiff: output the difference between date, time or duration"
  homepage "https://github.com/jftuga/dtdiff"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_darwin_amd64.tar.xz"
      sha256 "b32322e145aa110376668673905845d97740e48a84720ad109a1cec7eaa44272"

      def install
        bin.install "dtdiff"
      end
    end
    on_arm do
      url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_darwin_arm64.tar.xz"
      sha256 "35d17e45c98918326ee2b0f648c54f7ce37a7af5ee5e1973f6b9fe466b1043cb"

      def install
        bin.install "dtdiff"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_linux_amd64.tar.xz"
        sha256 "d094cc60ca0a4846406b006ab2751f1e9f1b40805336c68e7fe22a66477e85f4"

        def install
          bin.install "dtdiff"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/dtdiff/releases/download/v1.0.0/dtdiff_1.0.0_linux_arm64.tar.xz"
        sha256 "c90fe391207c311a01040d7f5ca5d542ef068cbeb36d3302465e72e65fff477c"

        def install
          bin.install "dtdiff"
        end
      end
    end
  end

  test do
    system "#{bin}/dtdiff -v"
  end
end
