# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dtmate < Formula
  desc "dtmate: output the difference between date, time or duration"
  homepage "https://github.com/jftuga/DateTimeMate"
  version "1.2.2"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/DateTimeMate/releases/download/v1.2.2/DateTimeMate_1.2.2_darwin_amd64.tar.xz"
      sha256 "da29fe9788ac082a7f0ffc91c96943cda345d5f96f0e7ffc11aa5e963d3ad6c8"

      def install
        bin.install "dtmate"
      end
    end
    on_arm do
      url "https://github.com/jftuga/DateTimeMate/releases/download/v1.2.2/DateTimeMate_1.2.2_darwin_arm64.tar.xz"
      sha256 "a09627b58ace603163675ecf42d085a054992895bfa9561a20457b06d33039b5"

      def install
        bin.install "dtmate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/DateTimeMate/releases/download/v1.2.2/DateTimeMate_1.2.2_linux_amd64.tar.xz"
        sha256 "4327a05d6d0184c2d31e4fb88ea7f89e04b7d899295714c8b4ac6453febaccd2"

        def install
          bin.install "dtmate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/DateTimeMate/releases/download/v1.2.2/DateTimeMate_1.2.2_linux_arm64.tar.xz"
        sha256 "749031b2f6c955cafb64d80806d298c2b494a01e4a4e9e0c9e5e76ff7247384c"

        def install
          bin.install "dtmate"
        end
      end
    end
  end

  test do
    system "#{bin}/dtmate -v"
  end
end
