# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freq < Formula
  desc "Display the frequency of each line in a file or from STDIN"
  homepage "https://github.com/jftuga/freq"
  version "1.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_darwin_amd64.tar.xz"
      sha256 "0d16a6b5fda3a1414a0d122c2cdc8ddf586cdb8888ad413843a8f287df4a65be"

      def install
        bin.install "freq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_darwin_arm64.tar.xz"
      sha256 "f84197a2cb4a86f17833664cc0fbdf0899486612725923ca4b8043377eff2fa0"

      def install
        bin.install "freq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_linux_arm64.tar.xz"
      sha256 "5b33e73d01daa04e6625bcd68800d60de1852c57300f626fa2488b4709a7b161"

      def install
        bin.install "freq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_linux_amd64.tar.xz"
      sha256 "2773ba24f1093d88504a3e29f448a90b3236c4240a98dc2e725a648f6f5818cf"

      def install
        bin.install "freq"
      end
    end
  end

  test do
    system "#{bin}/freq -v"
  end
end
