# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freq < Formula
  desc "Display the frequency of each line in a file or from STDIN"
  homepage "https://github.com/jftuga/freq"
  version "1.8.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_darwin_arm64.tar.xz"
      sha256 "0c6eeff8ea7a8e958f73b9fbb7c83bab4e72b10c798006469ed1640c0605c50b"

      def install
        bin.install "freq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_darwin_amd64.tar.xz"
      sha256 "e3e9d0f149717fb66e3412a05a4e7c30e019e750b3048d0ab47ae5ffc3dc9f4b"

      def install
        bin.install "freq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_linux_amd64.tar.xz"
      sha256 "ddd21d402b28fc9213efcde5d861cb45ca87f0c74858e21922e4bedc66dab5f2"

      def install
        bin.install "freq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/freq/releases/download/v1.8.2/freq_1.8.2_linux_arm64.tar.xz"
      sha256 "5a5b20b7320cc3587f7619ac50f4a6c08e3380a004b43b431eef86f6e9b492fe"

      def install
        bin.install "freq"
      end
    end
  end

  test do
    system "#{bin}/freq -v"
  end
end
