# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fstat < Formula
  desc "fstat: get info for a list of files across multiple directories"
  homepage "https://github.com/jftuga/fstat"
  version "2.6.13"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/fstat/releases/download/v2.6.13/fstat_2.6.13_darwin_amd64.tar.xz"
      sha256 "08a2345b9f61d9036be550a1e657746d9e0b271f2454ba891da1d957d87de4bc"

      def install
        bin.install "fstat"
      end
    end
    on_arm do
      url "https://github.com/jftuga/fstat/releases/download/v2.6.13/fstat_2.6.13_darwin_arm64.tar.xz"
      sha256 "3e753dc3eb568278c79ab895baf16712b9845689a944757e1473617881ffffb4"

      def install
        bin.install "fstat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/fstat/releases/download/v2.6.13/fstat_2.6.13_linux_amd64.tar.xz"
        sha256 "88b36edde175562a3c503679f44e7499b3ba2b96612ccf76d7316ecdc6e9a9f5"

        def install
          bin.install "fstat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/fstat/releases/download/v2.6.13/fstat_2.6.13_linux_arm64.tar.xz"
        sha256 "a7985b684263860c1cdf5b0b52205bf34b4b3de02a81543f668d6cf956510bab"

        def install
          bin.install "fstat"
        end
      end
    end
  end

  test do
    system "#{bin}/fstat -v"
  end
end
