# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostat < Formula
  desc "Display and set file timestamps"
  homepage "https://github.com/jftuga/gostat"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/gostat/releases/download/v1.1.0/gostat_1.1.0_darwin_amd64.tar.xz"
      sha256 "cb1fd7cf0aa142b3c7c4c965763411b7803e7e9b84613eb64cac8bdaccc5e01c"

      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/gostat/releases/download/v1.1.0/gostat_1.1.0_darwin_arm64.tar.xz"
      sha256 "88b2694ce580cc877494fdda0c181e1c50ea7c00bc3a095b4ae8439e71f7b8fe"

      def install
        bin.install "gostat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/gostat/releases/download/v1.1.0/gostat_1.1.0_linux_amd64.tar.xz"
      sha256 "8fe6e0ddebc38ee9832df4352ee23d9eb4648323d42996ef6edad22803b8b3fd"
      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/gostat/releases/download/v1.1.0/gostat_1.1.0_linux_arm64.tar.xz"
      sha256 "8fbf0445d306c346a35ed4b067004a97944b5fb5ceeec732aca05506088c8db4"
      def install
        bin.install "gostat"
      end
    end
  end

  test do
    system "#{bin}/gostat -v"
  end
end
