# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostat < Formula
  desc "Display and set file timestamps"
  homepage "https://github.com/jftuga/gostat"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.3/gostat_1.0.3_darwin_amd64.tar.xz"
      sha256 "4e58bc921d012256178096f440966314d1278e4b698a6668ea6e4e2ba8bb5bf2"

      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.3/gostat_1.0.3_darwin_arm64.tar.xz"
      sha256 "0780d856226956ea25876d13aab080ba3380413e967368e56d818367d800c053"

      def install
        bin.install "gostat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.3/gostat_1.0.3_linux_amd64.tar.xz"
      sha256 "5ea0f35a9fd3608c71347c8de9bb80bf2d81bb38362bd4fe50dcfaad316a9364"
      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.3/gostat_1.0.3_linux_arm64.tar.xz"
      sha256 "77dfa325476d43f9c0c2d651d4ed70caa4f19e372e3ddc24a17876c71db24e22"
      def install
        bin.install "gostat"
      end
    end
  end

  test do
    system "#{bin}/gostat -v"
  end
end
