# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostat < Formula
  desc "Display and set file timestamps"
  homepage "https://github.com/jftuga/gostat"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.2/gostat_1.0.2_darwin_amd64.tar.xz"
      sha256 "c1449a62266af6442fb863f9bc2647d13436ffd93dfa539649e67d54861e5a6f"

      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.2/gostat_1.0.2_darwin_arm64.tar.xz"
      sha256 "6d69d1c09d9362b14c7a56d551cd85c5ffb50b36d0c13c219f6eb97b7013f342"

      def install
        bin.install "gostat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.2/gostat_1.0.2_linux_amd64.tar.xz"
      sha256 "5793a028fae708f5a7aa751eba16b75f11199f5a60a77724b8f66492b9e45e55"

      def install
        bin.install "gostat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/gostat/releases/download/v1.0.2/gostat_1.0.2_linux_arm64.tar.xz"
      sha256 "73e93cf2b67b0da3b93186eec165e7eb5089de638d842bd8d27bfb1331e91e7d"

      def install
        bin.install "gostat"
      end
    end
  end

  test do
    system "#{bin}/gostat -v"
  end
end
