# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipinfo < Formula
  desc "Return IP address info including geographic location and distance when given IP address, email address, host name or URL "
  homepage "https://github.com/jftuga/ipinfo"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.2.0/ipinfo_1.2.0_darwin_amd64.tar.xz"
      sha256 "04757e4cc7ff35401651b1612bde42981dd54bd05dc3d99311483b9536baf6f6"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.2.0/ipinfo_1.2.0_darwin_arm64.tar.xz"
      sha256 "31c94ac3a669d3e61f70224d67c40402abbd5b4f777d516f10e727941aa95b67"

      def install
        bin.install "ipinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/ipinfo/releases/download/v1.2.0/ipinfo_1.2.0_linux_amd64.tar.xz"
        sha256 "907730819f0644dfcfcf8af08aea81edccbb7d06719f0baa621f0390e3e482fe"

        def install
          bin.install "ipinfo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/ipinfo/releases/download/v1.2.0/ipinfo_1.2.0_linux_arm64.tar.xz"
        sha256 "264bce797244a845bf4c96b75167eb8e7d7db0f879f00988e7c3ee90728c3daa"

        def install
          bin.install "ipinfo"
        end
      end
    end
  end

  test do
    system "#{bin}/ipinfo -v"
  end
end
