# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipinfo < Formula
  desc "Return IP address info including geographic location and distance when given IP address, email address, host name or URL "
  homepage "https://github.com/jftuga/ipinfo"
  version "1.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.1.4/ipinfo_1.1.4_darwin_amd64.tar.xz"
      sha256 "899b6c8b16bece8797d55b73e6be704fc159dc4768b7274982360a56d7de137a"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.1.4/ipinfo_1.1.4_darwin_arm64.tar.xz"
      sha256 "2267f982ea77fdc674c7014e696fef04617807de07ef769f666ed7bb93a0167e"

      def install
        bin.install "ipinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.1.4/ipinfo_1.1.4_linux_arm64.tar.xz"
      sha256 "b093f3343fb2c939b0299329f68a59f50d491989fb1185827287996cb39d0caa"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.1.4/ipinfo_1.1.4_linux_amd64.tar.xz"
      sha256 "dd75eb633e44802d708d71e4fb6ab0b991e39b663d452f048f146655a672488f"

      def install
        bin.install "ipinfo"
      end
    end
  end

  test do
    system "#{bin}/ipinfo -v"
  end
end
