# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipinfo < Formula
  desc "Return IP address info including geographic location and distance when given IP address, email address, host name or URL "
  homepage "https://github.com/jftuga/ipinfo"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.3.0/ipinfo_1.3.0_darwin_amd64.tar.xz"
      sha256 "b541f972ba56fb9e6843b835e01d42724ef039e90e00deab79c8cc3e15c60d85"

      def install
        bin.install "ipinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/ipinfo/releases/download/v1.3.0/ipinfo_1.3.0_darwin_arm64.tar.xz"
      sha256 "054e60a7da9d3dfee3221a8c06e792863776b32fba953e639c9e1ab9ef443ea9"

      def install
        bin.install "ipinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/ipinfo/releases/download/v1.3.0/ipinfo_1.3.0_linux_amd64.tar.xz"
        sha256 "ddbefaea79e9c7ba80ef28419b3cdc4c0092d7c8e5f638604d8f2334eaae6b53"

        def install
          bin.install "ipinfo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/ipinfo/releases/download/v1.3.0/ipinfo_1.3.0_linux_arm64.tar.xz"
        sha256 "123d0262a1e3eb93f4a1f61417fb37d98f8f20216b751503f6c19e935feae395"

        def install
          bin.install "ipinfo"
        end
      end
    end
  end

  test do
    system "#{bin}/ipinfo -v"
  end
end
