# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mtool < Formula
  desc "Swiss army knife CLI utility"
  homepage "https://github.com/jftuga/mtool"
  version "2.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/mtool/releases/download/v2.0.5/mtool_2.0.5_darwin_amd64.tar.xz"
      sha256 "198bc86ac1ecdad1ba566b1b01feab269bdc2fa2d78cf077823806cdae79198a"

      define_method(:install) do
        bin.install "mtool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/mtool/releases/download/v2.0.5/mtool_2.0.5_darwin_arm64.tar.xz"
      sha256 "b6622f7295c043393157e9f3f9b786338e157e2a00505d76ab0abbbe0166b45b"

      define_method(:install) do
        bin.install "mtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/mtool/releases/download/v2.0.5/mtool_2.0.5_linux_amd64.tar.xz"
      sha256 "a0e2d2bee61b6ea11f0e2a466bcbae8359a1c124cd542d4333c971bc1cc258bb"
      define_method(:install) do
        bin.install "mtool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/mtool/releases/download/v2.0.5/mtool_2.0.5_linux_arm64.tar.xz"
      sha256 "63373cada0ac5beb846a8376463b5064626392a80ff47a3740f106944eb399e3"
      define_method(:install) do
        bin.install "mtool"
      end
    end
  end

  test do
    system "#{bin}/mtool version"
  end
end
