# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nics < Formula
  desc "nics: Display information about Network Interface Cards (NICs)"
  homepage "https://github.com/jftuga/nics"
  version "1.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/nics/releases/download/v1.6.1/nics_1.6.1_darwin_amd64.tar.xz"
      sha256 "eedcba48922e2720126bde1b04779660f6f1b0c03057922b28023baf6622a988"

      def install
        bin.install "nics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/nics/releases/download/v1.6.1/nics_1.6.1_darwin_arm64.tar.xz"
      sha256 "160a6a96264d8206bad927a048ce87736f340689bc56f065a043e5bfb0001f63"

      def install
        bin.install "nics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/nics/releases/download/v1.6.1/nics_1.6.1_linux_amd64.tar.xz"
        sha256 "ca5e6af6be703f864af365133c5c1a6a15928becf0c02d713bad456776d259c6"

        def install
          bin.install "nics"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/nics/releases/download/v1.6.1/nics_1.6.1_linux_arm64.tar.xz"
        sha256 "127357f8a4e959acfb34100841730ec01b6a73ed1d9a6758f0c532e8ca7d6371"

        def install
          bin.install "nics"
        end
      end
    end
  end

  test do
    system "#{bin}/nics -v"
  end
end
