# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nics < Formula
  desc "nics: Display information about Network Interface Cards (NICs)"
  homepage "https://github.com/jftuga/nics"
  version "1.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/nics/releases/download/v1.7.0/nics_1.7.0_darwin_amd64.tar.xz"
      sha256 "71ded5c4c9c71e79b0278216fa8c495a15599273e76a3417809b795edd8f75f6"

      define_method(:install) do
        bin.install "nics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/nics/releases/download/v1.7.0/nics_1.7.0_darwin_arm64.tar.xz"
      sha256 "9457e9b690fa4221a301ce7cd05538b5fbb4625bb5273712509f9353bf6a99e5"

      define_method(:install) do
        bin.install "nics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/nics/releases/download/v1.7.0/nics_1.7.0_linux_amd64.tar.xz"
      sha256 "b8dfd63edc355cde0e9707c20ff7503782b71219fba16cc5a477ca716a94cbe7"
      define_method(:install) do
        bin.install "nics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/nics/releases/download/v1.7.0/nics_1.7.0_linux_arm64.tar.xz"
      sha256 "95a33646fc8f950ecbacfa4ff169fb8534cd0d8ce53c7a456e1c4852188c258a"
      define_method(:install) do
        bin.install "nics"
      end
    end
  end

  test do
    system "#{bin}/nics -v"
  end
end
