# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nics < Formula
  desc "nics: Display information about Network Interface Cards (NICs)"
  homepage "https://github.com/jftuga/nics"
  version "1.5.0"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/nics/releases/download/v1.5.0/nics_1.5.0_darwin_amd64.tar.xz"
      sha256 "a4a78034c74c6cec8a9a4977a0cbfda348fba3eb7fea80b63d7e781c3e9dcaaf"

      def install
        bin.install "nics"
      end
    end
    on_arm do
      url "https://github.com/jftuga/nics/releases/download/v1.5.0/nics_1.5.0_darwin_arm64.tar.xz"
      sha256 "fea29a99e1233489bfc3d94be6c79b0cc2d68ebddf7c27670ede01fe850a0a93"

      def install
        bin.install "nics"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/nics/releases/download/v1.5.0/nics_1.5.0_linux_amd64.tar.xz"
        sha256 "1b41f2d4d371be1ec062a26024657f4ca43c319ecbb7683336306df8b8727566"

        def install
          bin.install "nics"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/nics/releases/download/v1.5.0/nics_1.5.0_linux_arm64.tar.xz"
        sha256 "ac8a0f9c307d270991e30ca0fd1b6ea6c6f505138eab0361aba1764a9a1f8dc9"

        def install
          bin.install "nics"
        end
      end
    end
  end

  test do
    system "#{bin}/nics -v"
  end
end
