# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randrange < Formula
  desc "CLI for computing statistics"
  homepage "https://github.com/jftuga/randrange"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/randrange/releases/download/v0.3.1/randrange_0.3.1_darwin_amd64.tar.xz"
      sha256 "0fd4b000bfa90c1bcaf3a304ba62bf123f80529f18e60f5d71a1e3bdf7e64574"

      def install
        bin.install "randrange"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/randrange/releases/download/v0.3.1/randrange_0.3.1_darwin_arm64.tar.xz"
      sha256 "0228c7e5e26885a962f9d4a162d5b9fc4611d6bc81b7b2d4a6e7334751f6f6db"

      def install
        bin.install "randrange"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/randrange/releases/download/v0.3.1/randrange_0.3.1_linux_amd64.tar.xz"
      sha256 "6b371b49c2b2dbb1ed0be1523f6a76d375dd3b8b37d9e7e56aeb6325001dda4b"
      def install
        bin.install "randrange"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/randrange/releases/download/v0.3.1/randrange_0.3.1_linux_arm64.tar.xz"
      sha256 "795c3e47fd0a5123919b55d1a01f8054315a43467841c64ccc1804e1ce371c07"
      def install
        bin.install "randrange"
      end
    end
  end

  test do
    system "#{bin}/randrange -version"
  end
end
