# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnsPublish < Formula
  desc "command line tool to send message or file to AWS SNS topic subscribers"
  homepage "https://github.com/jftuga/sns_publish"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/sns_publish/releases/download/v1.2.0/sns_publish_1.2.0_darwin_arm64.tar.xz"
      sha256 "2396159108815aa1578c420a6a167ee3fe895319eefed19d0380a5d444896a20"

      def install
        bin.install "sns_publish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/sns_publish/releases/download/v1.2.0/sns_publish_1.2.0_darwin_amd64.tar.xz"
      sha256 "fee7f491731e082725007538492d37da1ae81ec916d5f8ea8dea7ce8ad7e87af"

      def install
        bin.install "sns_publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/sns_publish/releases/download/v1.2.0/sns_publish_1.2.0_linux_arm64.tar.xz"
      sha256 "e72256bdec569e2f2f6f276fbba13d3ef4ee82f9239437e44b268d29341afc1a"

      def install
        bin.install "sns_publish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/sns_publish/releases/download/v1.2.0/sns_publish_1.2.0_linux_amd64.tar.xz"
      sha256 "5db795ee351a335f1f69dc0158437987a19e43a62a4d9b424634d8879dcf205d"

      def install
        bin.install "sns_publish"
      end
    end
  end

  test do
    system "#{bin}/sns_publish -v"
  end
end
