# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stats < Formula
  desc "CLI for computing statistics"
  homepage "https://github.com/jftuga/go-stats-calculator"
  version "1.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.9.0/go-stats-calculator_1.9.0_darwin_amd64.tar.xz"
      sha256 "d309130d8019afa42291babd202658c4db914a59a4d7a389ec1ac1e6c91cf2e8"

      def install
        bin.install "stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.9.0/go-stats-calculator_1.9.0_darwin_arm64.tar.xz"
      sha256 "ce18f2b38cae33321972e9bfc1ecd479304591206495d4315c65e8e348750f3f"

      def install
        bin.install "stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.9.0/go-stats-calculator_1.9.0_linux_amd64.tar.xz"
      sha256 "b5f8131176595dfc39a61ad96023fab03f028f3afdd0b65b5ca5d3d5d613d8bf"
      def install
        bin.install "stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.9.0/go-stats-calculator_1.9.0_linux_arm64.tar.xz"
      sha256 "d24dde3a1c6804a4114975e505c6f62c41230d87bdf8fa14cda6a68971112cb2"
      def install
        bin.install "stats"
      end
    end
  end

  test do
    system "#{bin}/stats -v"
  end
end
