# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stats < Formula
  desc "CLI for computing statistics"
  homepage "https://github.com/jftuga/go-stats-calculator"
  version "1.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.11.0/go-stats-calculator_1.11.0_darwin_amd64.tar.xz"
      sha256 "a1ed36852e1237844e12641a02301ec04137fb404a6fdec7c0e37436303d9c16"

      define_method(:install) do
        bin.install "stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.11.0/go-stats-calculator_1.11.0_darwin_arm64.tar.xz"
      sha256 "c825631e01187a3d255178897f74638dd73824818c267eeb32adf9b97a1333bd"

      define_method(:install) do
        bin.install "stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.11.0/go-stats-calculator_1.11.0_linux_amd64.tar.xz"
      sha256 "f4d478563d947f0038f0bb501722fdac0059b673a9071a697135e089cb8fae05"
      define_method(:install) do
        bin.install "stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.11.0/go-stats-calculator_1.11.0_linux_arm64.tar.xz"
      sha256 "bdc959758857bd34698e5e77a5a37d4e16518821cde3e004f701f46da924f4c3"
      define_method(:install) do
        bin.install "stats"
      end
    end
  end

  test do
    system "#{bin}/stats -v"
  end
end
