# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stats < Formula
  desc "CLI for computing statistics"
  homepage "https://github.com/jftuga/go-stats-calculator"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.6.0/go-stats-calculator_1.6.0_darwin_amd64.tar.xz"
      sha256 "542298ca54f05b802d2d9fe1136cd4f43cc3c6cd5633da8b4d1392fc7615bf9b"

      def install
        bin.install "stats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.6.0/go-stats-calculator_1.6.0_darwin_arm64.tar.xz"
      sha256 "5c0d3be55d8d4639c5359362fbf699cdc2077f470a9dfdd47457b558b65dc794"

      def install
        bin.install "stats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.6.0/go-stats-calculator_1.6.0_linux_amd64.tar.xz"
      sha256 "2ebf0362374e8ee691de88ada2e82ed2070d3d262dc741732ece74afd509f33a"
      def install
        bin.install "stats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jftuga/go-stats-calculator/releases/download/v1.6.0/go-stats-calculator_1.6.0_linux_arm64.tar.xz"
      sha256 "b43183ada5a372ed245f209a1dca5a7cf816b876287c9cc658f09009c8352c7b"
      def install
        bin.install "stats"
      end
    end
  end

  test do
    system "#{bin}/stats -v"
  end
end
