# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timeit < Formula
  desc "timeit: a CLI tool used to time the duration of the given command"
  homepage "https://github.com/jftuga/timeit"
  version "1.3.2"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/timeit/releases/download/v1.3.2/timeit_1.3.2_darwin_amd64.tar.xz"
      sha256 "d235d6de4a069f6bf38a934950ad77f8ad53d7579e6812abf60b4aedc4fd8eb3"

      def install
        bin.install "timeit"
      end
    end
    on_arm do
      url "https://github.com/jftuga/timeit/releases/download/v1.3.2/timeit_1.3.2_darwin_arm64.tar.xz"
      sha256 "1168dd00fe82c88b6deca2bdb49aede646d201a8c314f2fa33d045115cc6e6a1"

      def install
        bin.install "timeit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/timeit/releases/download/v1.3.2/timeit_1.3.2_linux_amd64.tar.xz"
        sha256 "cbc8e5ac773f7fb10f9729dafc501c8868ee356512e2788712e47ccdb12f4b04"

        def install
          bin.install "timeit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jftuga/timeit/releases/download/v1.3.2/timeit_1.3.2_linux_arm64.tar.xz"
        sha256 "e1a3171f4e2727d0cdf852d62b67b1e106b98869dc53eb9b2b0bec7bec847239"

        def install
          bin.install "timeit"
        end
      end
    end
  end

  test do
    system "#{bin}/timeit -v"
  end
end
