# This file was generated by GoReleaser. DO NOT EDIT.
cask "wrapline" do
  name "wrapline"
  desc "CLI tool that wraps each line of input with a specified delimiter"
  homepage "https://github.com/jftuga/wrapline"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wrapline"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_darwin_amd64.tar.xz"
      sha256 "7498b00bedf6674f95d0bb34901b626b463b959f4ba826da69000932fc7d3844"
    end
    on_arm do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_darwin_arm64.tar.xz"
      sha256 "37c58543fe862f72c973f75c4b1d9e67088785b53022733c694a975631a22b6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_linux_amd64.tar.xz"
      sha256 "d8af89eba4bc563754de823f7d34f7bd738f22d680b25e64e3f0437b43ba6f31"
    end
    on_arm do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_linux_arm64.tar.xz"
      sha256 "dfc6db110ad332a9730800a7b370e86dc791a79723030918ea850e2b3c926a86"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wrapline"]
    end
  end

  # No zap stanza required
end
