# This file was generated by GoReleaser. DO NOT EDIT.
cask "wrapline" do
  name "wrapline"
  desc "CLI tool that wraps each line of input with a specified delimiter"
  homepage "https://github.com/jftuga/wrapline"
  version "1.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wrapline_1.1.6_darwin_arm64/wrapline"

  on_macos do
    on_intel do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_darwin_amd64.tar.xz",
        verified: "github.com/jftuga/wrapline"
      sha256 "f0fcd5120a7d1db501626a50c645e2827469e055c6d54cd29f3bf6b035849856"
    end
    on_arm do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_darwin_arm64.tar.xz",
        verified: "github.com/jftuga/wrapline"
      sha256 "5026738a2a091c90fa6ca40ddd02beacda9765bfbbf59c77609fba70625e9fcf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_linux_amd64.tar.xz",
        verified: "github.com/jftuga/wrapline"
      sha256 "4f58823b32567ab2d861c5a77ebaec1c532234742970b009239d6c02708ec095"
    end
    on_arm do
      url "https://github.com/jftuga/wrapline/releases/download/v#{version}/wrapline_#{version}_linux_arm64.tar.xz",
        verified: "github.com/jftuga/wrapline"
      sha256 "eb043a2b8bd6a9b84f90dc6c8ea0063a57834006cf42f09f65166d4a315417bc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wrapline_1.1.6_darwin_arm64/wrapline"]
    end
  end

  # No zap stanza required
end
